Repository grote/osm2gtfs, pull requests merged in 2018-03, with the labels that each got.

#83 Introduce ISO 3166-2 country codes for creator directories
  .gitignore
  README.md
  osm2gtfs/core/configuration.py
  osm2gtfs/core/creator_factory.py
  osm2gtfs/creators/br_florianopolis/__init__.py
  osm2gtfs/creators/br_florianopolis/config.json
  osm2gtfs/creators/br_florianopolis/routes_creator_br_florianopolis.py
  osm2gtfs/creators/br_florianopolis/stops_creator_br_florianopolis.py
  osm2gtfs/creators/br_florianopolis/trips_creator_br_florianopolis.py
  osm2gtfs/creators/cr_gam/__init__.py
  osm2gtfs/creators/cr_gam/config.json
  osm2gtfs/creators/cr_gam/routes_creator_cr_gam.py
  osm2gtfs/creators/cr_gam/stops_creator_cr_gam.py
  osm2gtfs/creators/cr_gam/trips_creator_cr_gam.py
  osm2gtfs/creators/gh_accra/__init__.py
  osm2gtfs/creators/gh_accra/config.json
  osm2gtfs/creators/gh_accra/routes_creator_gh_accra.py
  osm2gtfs/creators/gh_accra/schedule_creator_gh_accra.py
  osm2gtfs/creators/gh_accra/stops_creator_gh_accra.py
  osm2gtfs/creators/gh_accra/trips_creator_gh_accra.py
  osm2gtfs/creators/ni_esteli/config.json
  osm2gtfs/creators/ni_managua/config.json
  osm2gtfs/tests/README.md
  osm2gtfs/tests/core/__init__.py
  osm2gtfs/tests/core/tests_creator_factory.py
  osm2gtfs/tests/creators/__init__.py
  osm2gtfs/tests/creators/fixtures/gh_accra/gh_accra_tests.zip.ref
  osm2gtfs/tests/creators/fixtures/gh_accra/overpass-routes.xml
  osm2gtfs/tests/creators/fixtures/gh_accra/overpass-stops.xml
  osm2gtfs/tests/creators/tests_gh_accra.py
Labels: enhancement, ready

#124 Bugfix: check for NoneType in OSM Connector
  osm2gtfs/core/osm_connector.py
Labels: bug, ready

#126 Fixed some functions in StandardTripsCreator
  osm2gtfs/creators/trips_creator.py
Labels: High Priority, enhancement, ready

#123 Support multiple values for the same OSM tag
  osm2gtfs/core/osm_connector.py
Labels: enhancement, ready

#127 Remove unused stops and routes
  osm2gtfs/creators/routes_creator.py
  osm2gtfs/creators/stops_creator.py
  osm2gtfs/osm2gtfs.py
Labels: enhancement, ready

#132 Add check for known OSM route types
  osm2gtfs/core/elements.py
Labels: enhancement, ready

#133 Abstract test classes to share common logic between creators
  .travis.yml
  osm2gtfs/core/osm_connector.py
  osm2gtfs/tests/README.md
  osm2gtfs/tests/creators/creators_tests.py
  osm2gtfs/tests/creators/fixtures/gh_accra/gh_accra_gtfs.zip.ref
  osm2gtfs/tests/creators/fixtures/gh_accra/gh_accra_tests.zip.ref
  osm2gtfs/tests/creators/fixtures/gh_accra/queries.txt
  osm2gtfs/tests/creators/fixtures/ni_managua/queries.txt
  osm2gtfs/tests/creators/tests_gh_accra.py
  osm2gtfs/tests/creators/tests_ni_managua.py
Labels: enhancement, ready
